package com.pinknote.app.presentation.localization

import androidx.compose.runtime.staticCompositionLocalOf
import com.pinknote.app.domain.model.AppLanguage

data class AppStrings(
    val languageCode: AppLanguage,
    val home: String,
    val calendar: String,
    val reminders: String,
    val profile: String,
    val settings: String,
    val hello: String,
    val today: String,
    val viewPrediction: String,
    val nextPeriod: String,
    val ovulation: String,
    val cycleDay: String,
    val fertilityToday: String,
    val estimated: String,
    val byCycle: String,
    val current: String,
    val todayTips: String,
    val todayTipsBody: String,
    val quickStats: String,
    val cycle: String,
    val period: String,
    val recent: String,
    val configured: String,
    val noData: String,
    val averagePain: String,
    val tracking: String,
    val months: String,
    val painChart: String,
    val cycleSetup: String,
    val firstCycleSetupPrompt: String,
    val editCycleSetupPrompt: String,
    val lastPeriodDateLabel: String,
    val optionalCycleSetupHint: String,
    val cycleLengthLabel: String,
    val periodLengthLabel: String,
    val saveCycleSettings: String,
    val invalidDate: String,
    val invalidCycleLength: String,
    val invalidPeriodLength: String,
    val periodShorterThanCycle: String,
    val theme: String,
    val themeSystem: String,
    val themeLight: String,
    val themeDark: String,
    val language: String,
    val notifications: String,
    val adminConsole: String,
    val sendPasswordEmail: String,
    val logout: String,
    val deleteAccount: String,
    val about: String,
    val version: String,
    val developer: String,
    val contact: String,
    val medicalDisclaimer: String,
    val medicalDisclaimerBody: String,
    val loginTitle: String,
    val loginSubtitle: String,
    val email: String,
    val password: String,
    val login: String,
    val loginWithGoogle: String,
    val forgotPassword: String,
    val createAccount: String,
    val registerTitle: String,
    val registerSubtitle: String,
    val name: String,
    val register: String,
    val alreadyHaveAccount: String,
    val personalCycleJournal: String,
    val privacy: String,
    val easyTracking: String,
    val personal: String,
    val processing: String,
    val languageVietnamese: String,
    val languageEnglish: String,
    val passwordResetTitle: String,
    val passwordResetBody: String,
    val registeredEmail: String,
    val sendEmail: String,
    val cancel: String,
    val nameRequired: String,
    val emailRequired: String,
    val registeredEmailRequired: String,
    val invalidEmail: String,
    val passwordTooShort: String,
    val passwordResetSentMessage: String,
    val googleMissingIdToken: String,
    val googleNoTokenWithResultCode: String,
    val googleConfigError: String,
    val googleNetworkError: String,
    val googleSignInCancelled: String,
    val googleSignInInProgress: String,
    val googleSignInFailed: String,
    val googleSignInFailedWithCode: String,
    val deleteAccountConfirmTitle: String,
    val deleteAccountConfirmBody: String,
    val deleteAccountConfirmInstruction: String,
    val deleteAccountPermanent: String,
    val openSourceLibraries: String,
    val privacyPolicyBody: String
)

val LocalAppStrings = staticCompositionLocalOf { viStrings }

fun appStrings(language: AppLanguage): AppStrings {
    return when (language) {
        AppLanguage.VI -> viStrings
        AppLanguage.EN -> enStrings
    }
}

fun AppStrings.languageLabel(language: AppLanguage): String {
    return when (language) {
        AppLanguage.VI -> languageVietnamese
        AppLanguage.EN -> languageEnglish
    }
}

private val viStrings = AppStrings(
    languageCode = AppLanguage.VI,
    home = "Trang chủ",
    calendar = "Lịch",
    reminders = "Nhắc",
    profile = "Hồ sơ",
    settings = "Cài đặt",
    hello = "Xin chào",
    today = "Hôm nay",
    viewPrediction = "Xem dự đoán",
    nextPeriod = "Kỳ tiếp theo",
    ovulation = "Rụng trứng",
    cycleDay = "Ngày chu kỳ",
    fertilityToday = "Thụ thai hôm nay",
    estimated = "Dự kiến",
    byCycle = "Theo chu kỳ",
    current = "Hiện tại",
    todayTips = "Gợi ý hôm nay",
    todayTipsBody = "Uống đủ nước, ngủ đúng giờ và ghi lại triệu chứng. Dữ liệu nhỏ mỗi ngày giúp dự đoán dễ tin hơn.",
    quickStats = "Thống kê nhanh",
    cycle = "Chu kỳ",
    period = "Hành kinh",
    recent = "Gần nhất",
    configured = "Thiết lập",
    noData = "Chưa có",
    averagePain = "Mức đau TB",
    tracking = "Theo dõi",
    months = "tháng",
    painChart = "Biểu đồ mức đau",
    cycleSetup = "Thiết lập chu kỳ",
    firstCycleSetupPrompt = "Chỉ cần nhập ngày bắt đầu kỳ gần nhất để Pink Note dự đoán chu kỳ.",
    editCycleSetupPrompt = "Bạn có thể chỉnh lại bất cứ lúc nào.",
    lastPeriodDateLabel = "Ngày bắt đầu gần nhất yyyy-MM-dd",
    optionalCycleSetupHint = "Chu kỳ và hành kinh là tùy chọn. Nếu bỏ trống, Pink Note sẽ dùng mức trung bình.",
    cycleLengthLabel = "Chu kỳ",
    periodLengthLabel = "Hành kinh",
    saveCycleSettings = "Lưu thiết lập",
    invalidDate = "Hãy nhập ngày theo định dạng yyyy-MM-dd.",
    invalidCycleLength = "Hãy nhập độ dài chu kỳ hợp lệ.",
    invalidPeriodLength = "Hãy nhập số ngày hành kinh hợp lệ.",
    periodShorterThanCycle = "Số ngày hành kinh phải nhỏ hơn độ dài chu kỳ.",
    theme = "Giao diện",
    themeSystem = "Theo hệ thống",
    themeLight = "Sáng",
    themeDark = "Tối",
    language = "Ngôn ngữ",
    notifications = "Thông báo",
    adminConsole = "Quản trị ứng dụng",
    sendPasswordEmail = "Gửi email đổi mật khẩu",
    logout = "Đăng xuất",
    deleteAccount = "Xóa tài khoản",
    about = "Về PinkNote",
    version = "Phiên bản",
    developer = "Nhà phát triển",
    contact = "Liên hệ",
    medicalDisclaimer = "Lưu ý y tế",
    medicalDisclaimerBody = "This application is intended for educational and personal health tracking purposes only.\n\nIt does not provide medical diagnosis, treatment, or professional medical advice.\n\nPredictions of menstruation, ovulation, and fertility are estimates based on user-entered data and statistical models.\n\nThe application should not be used as a method of contraception or pregnancy planning.\n\nPlease consult a qualified healthcare professional for any medical concerns.",
    loginTitle = "Chào mừng trở lại",
    loginSubtitle = "Tiếp tục theo dõi chu kỳ, nhật ký sức khỏe và các nhắc nhở quan trọng của bạn.",
    email = "Email",
    password = "Mật khẩu",
    login = "Đăng nhập",
    loginWithGoogle = "Đăng nhập bằng Google",
    forgotPassword = "Quên mật khẩu",
    createAccount = "Tạo tài khoản",
    registerTitle = "Tạo tài khoản",
    registerSubtitle = "Bắt đầu hồ sơ Pink Note để dự đoán chu kỳ và lưu nhật ký cá nhân mỗi ngày.",
    name = "Tên",
    register = "Đăng ký",
    alreadyHaveAccount = "Đã có tài khoản",
    personalCycleJournal = "Nhật ký chu kỳ cá nhân",
    privacy = "Riêng tư",
    easyTracking = "Dễ theo dõi",
    personal = "Cá nhân",
    processing = "Đang xử lý",
    languageVietnamese = "Tiếng Việt",
    languageEnglish = "English",
    passwordResetTitle = "Đặt lại mật khẩu",
    passwordResetBody = "Nhập email đã đăng ký. PinkNote sẽ gửi email chứa mã/link đặt lại mật khẩu để bạn tạo mật khẩu mới.",
    registeredEmail = "Email đã đăng ký",
    sendEmail = "Gửi email",
    cancel = "Hủy",
    nameRequired = "Hãy nhập tên của bạn.",
    emailRequired = "Hãy nhập email.",
    registeredEmailRequired = "Hãy nhập email đã đăng ký.",
    invalidEmail = "Email chưa đúng định dạng.",
    passwordTooShort = "Mật khẩu cần ít nhất 6 ký tự.",
    passwordResetSentMessage = "Nếu %s đã đăng ký PinkNote, email đặt lại mật khẩu đã được gửi. Hãy kiểm tra Hộp thư đến hoặc Spam.",
    googleMissingIdToken = "Không lấy được Google ID token. Hãy kiểm tra SHA-1/SHA-256 trong Firebase và tải lại google-services.json.",
    googleNoTokenWithResultCode = "Google chưa trả token cho app (resultCode=%d). Hãy kiểm tra provider Google, SHA-1/SHA-256 và tải lại google-services.json.",
    googleConfigError = "Google Sign-In lỗi cấu hình. Hãy thêm SHA-1/SHA-256 debug vào Firebase, tải lại google-services.json rồi cài lại app.",
    googleNetworkError = "Không thể kết nối Google. Hãy kiểm tra internet, ngày giờ thiết bị và Google Play Services.",
    googleSignInCancelled = "Bạn đã hủy đăng nhập Google.",
    googleSignInInProgress = "Google Sign-In đang xử lý, hãy thử lại sau vài giây.",
    googleSignInFailed = "Google Sign-In thất bại. Hãy kiểm tra SHA-1/SHA-256 và provider Google trong Firebase Authentication.",
    googleSignInFailedWithCode = "Google Sign-In thất bại (mã %d: %s).",
    deleteAccountConfirmTitle = "Xác nhận xóa tài khoản",
    deleteAccountConfirmBody = "Thao tác này sẽ xóa tài khoản, hồ sơ, chu kỳ, nhật ký, nhắc nhở và dữ liệu đã đồng bộ của bạn. Không thể hoàn tác.",
    deleteAccountConfirmInstruction = "Nhập %s để xác nhận.",
    deleteAccountPermanent = "Xóa vĩnh viễn",
    openSourceLibraries = "Thư viện mã nguồn mở: Kotlin, Jetpack Compose, Hilt, Room, Firebase, WorkManager, MPAndroidChart.",
    privacyPolicyBody = "Chính sách quyền riêng tư: dữ liệu cục bộ và dữ liệu Firebase được dùng cho tài khoản, chu kỳ, nhắc nhở và tính năng theo dõi sức khỏe cá nhân."
)

private val enStrings = AppStrings(
    languageCode = AppLanguage.EN,
    home = "Home",
    calendar = "Calendar",
    reminders = "Reminders",
    profile = "Profile",
    settings = "Settings",
    hello = "Hello",
    today = "Today",
    viewPrediction = "View prediction",
    nextPeriod = "Next period",
    ovulation = "Ovulation",
    cycleDay = "Cycle day",
    fertilityToday = "Fertility today",
    estimated = "Estimated",
    byCycle = "By cycle",
    current = "Current",
    todayTips = "Today's tips",
    todayTipsBody = "Drink enough water, sleep on time, and record symptoms. Small daily notes make predictions more reliable.",
    quickStats = "Quick stats",
    cycle = "Cycle",
    period = "Period",
    recent = "Recent",
    configured = "Configured",
    noData = "No data",
    averagePain = "Avg pain",
    tracking = "Tracking",
    months = "months",
    painChart = "Pain chart",
    cycleSetup = "Cycle setup",
    firstCycleSetupPrompt = "Enter only your latest period start date to let Pink Note predict your cycle.",
    editCycleSetupPrompt = "You can update this anytime.",
    lastPeriodDateLabel = "Last period start yyyy-MM-dd",
    optionalCycleSetupHint = "Cycle and period length are optional. If left blank, Pink Note will use average defaults.",
    cycleLengthLabel = "Cycle",
    periodLengthLabel = "Period",
    saveCycleSettings = "Save settings",
    invalidDate = "Enter a date in yyyy-MM-dd format.",
    invalidCycleLength = "Enter a valid cycle length.",
    invalidPeriodLength = "Enter a valid period length.",
    periodShorterThanCycle = "Period length must be shorter than cycle length.",
    theme = "Theme",
    themeSystem = "System",
    themeLight = "Light",
    themeDark = "Dark",
    language = "Language",
    notifications = "Notifications",
    adminConsole = "Admin console",
    sendPasswordEmail = "Send password change email",
    logout = "Log out",
    deleteAccount = "Delete account",
    about = "About PinkNote",
    version = "Version",
    developer = "Developer",
    contact = "Contact",
    medicalDisclaimer = "Medical Disclaimer",
    medicalDisclaimerBody = "This application is intended for educational and personal health tracking purposes only.\n\nIt does not provide medical diagnosis, treatment, or professional medical advice.\n\nPredictions of menstruation, ovulation, and fertility are estimates based on user-entered data and statistical models.\n\nThe application should not be used as a method of contraception or pregnancy planning.\n\nPlease consult a qualified healthcare professional for any medical concerns.",
    loginTitle = "Welcome back",
    loginSubtitle = "Continue tracking your cycle, health journal, and important reminders.",
    email = "Email",
    password = "Password",
    login = "Log in",
    loginWithGoogle = "Continue with Google",
    forgotPassword = "Forgot password",
    createAccount = "Create account",
    registerTitle = "Create account",
    registerSubtitle = "Start your Pink Note profile to predict cycles and keep a personal daily journal.",
    name = "Name",
    register = "Sign up",
    alreadyHaveAccount = "Already have an account",
    personalCycleJournal = "Personal cycle journal",
    privacy = "Private",
    easyTracking = "Easy tracking",
    personal = "Personal",
    processing = "Processing",
    languageVietnamese = "Vietnamese",
    languageEnglish = "English",
    passwordResetTitle = "Reset password",
    passwordResetBody = "Enter your registered email. PinkNote will send an email with a reset code/link so you can create a new password.",
    registeredEmail = "Registered email",
    sendEmail = "Send email",
    cancel = "Cancel",
    nameRequired = "Enter your name.",
    emailRequired = "Enter your email.",
    registeredEmailRequired = "Enter your registered email.",
    invalidEmail = "Email format is invalid.",
    passwordTooShort = "Password must be at least 6 characters.",
    passwordResetSentMessage = "If %s is registered with PinkNote, a password reset email has been sent. Check your Inbox or Spam folder.",
    googleMissingIdToken = "Could not get the Google ID token. Check SHA-1/SHA-256 in Firebase and download google-services.json again.",
    googleNoTokenWithResultCode = "Google did not return a token for the app (resultCode=%d). Check the Google provider, SHA-1/SHA-256, and download google-services.json again.",
    googleConfigError = "Google Sign-In is misconfigured. Add the debug SHA-1/SHA-256 to Firebase, download google-services.json again, then reinstall the app.",
    googleNetworkError = "Could not connect to Google. Check your internet connection, device date/time, and Google Play Services.",
    googleSignInCancelled = "You cancelled Google sign-in.",
    googleSignInInProgress = "Google Sign-In is already in progress. Try again in a few seconds.",
    googleSignInFailed = "Google Sign-In failed. Check SHA-1/SHA-256 and the Google provider in Firebase Authentication.",
    googleSignInFailedWithCode = "Google Sign-In failed (code %d: %s).",
    deleteAccountConfirmTitle = "Confirm account deletion",
    deleteAccountConfirmBody = "This will delete your account, profile, cycle, journal, reminders, and synced data. This cannot be undone.",
    deleteAccountConfirmInstruction = "Enter %s to confirm.",
    deleteAccountPermanent = "Delete permanently",
    openSourceLibraries = "Open-source libraries: Kotlin, Jetpack Compose, Hilt, Room, Firebase, WorkManager, MPAndroidChart.",
    privacyPolicyBody = "Privacy policy: local app data and Firebase data are used for account, cycle, reminder, and personal health tracking features."
)
